### ISSUE TITLE
No working in new Fronius Page

### ISSUE THREAD

**Issue by Coopermine** [MrAlexand0r/solarweb-scraper#1]
Hello

It seems that does not work on the new Fronius page the "pvSysId" handle normal.
But values ​​do not come. It looks like the Day / Production page no longer exists.

![image](https://user-images.githubusercontent.com/7460802/53367718-a5d0ab80-3925-11e9-9832-494bc43f2f7b.png)

**Comment by gratzl-dev** [comment]
Hello,
I'm sorry about that but this repository is no longer maintained. If you still need it I can only suggest to fork it and to fix it yourself.
